//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:soap-fault:details")]
    public partial class FaultDetail
    {
        
        private string errorMessageField;
        
        private string requestIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string requestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode", ConfigurationName="ServiceReference1.wsPeriodeObj")]
    public interface wsPeriodeObj
    {
        
        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Wrappernamespace (http://www.virtic.com/xmlns/virsapPeriode/wsPeriode) der Nachricht Connect_wsPeriodeRequest nicht mit dem Standardwert (http://www.virtic.com/xmlns/virsapPeriode) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.Connect_wsPeriodeResponse Connect_wsPeriode(ServiceReference1.Connect_wsPeriodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.Connect_wsPeriodeResponse> Connect_wsPeriodeAsync(ServiceReference1.Connect_wsPeriodeRequest request);
        
        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Wrappernamespace (http://www.virtic.com/xmlns/virsapPeriode/wsPeriode) der Nachricht Release_wsPeriodeRequest nicht mit dem Standardwert (http://www.virtic.com/xmlns/virsapPeriode) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.Release_wsPeriodeResponse Release_wsPeriode(ServiceReference1.Release_wsPeriodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.Release_wsPeriodeResponse> Release_wsPeriodeAsync(ServiceReference1.Release_wsPeriodeRequest request);
        
        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Wrappernamespace (http://www.virtic.com/xmlns/virsapPeriode/wsPeriode) der Nachricht CreatePO_periodeRequest nicht mit dem Standardwert (http://www.virtic.com/xmlns/virsapPeriode) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.CreatePO_periodeResponse CreatePO_periode(ServiceReference1.CreatePO_periodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CreatePO_periodeResponse> CreatePO_periodeAsync(ServiceReference1.CreatePO_periodeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.virtic.com/xmlns/virsapPeriode/wsPeriode")]
    public partial class wsPeriodeID
    {
        
        private string uUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Connect_wsPeriode", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/wsPeriode", IsWrapped=true)]
    public partial class Connect_wsPeriodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/wsPeriode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/wsPeriode", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/wsPeriode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string appServerInfo;
        
        public Connect_wsPeriodeRequest()
        {
        }
        
        public Connect_wsPeriodeRequest(string userId, string password, string appServerInfo)
        {
            this.userId = userId;
            this.password = password;
            this.appServerInfo = appServerInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Connect_wsPeriodeResponse", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/wsPeriode", IsWrapped=true)]
    public partial class Connect_wsPeriodeResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/wsPeriode")]
        public ServiceReference1.wsPeriodeID wsPeriodeID;
        
        public Connect_wsPeriodeResponse()
        {
        }
        
        public Connect_wsPeriodeResponse(ServiceReference1.wsPeriodeID wsPeriodeID)
        {
            this.wsPeriodeID = wsPeriodeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Release_wsPeriode", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/wsPeriode", IsWrapped=true)]
    public partial class Release_wsPeriodeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/wsPeriode")]
        public ServiceReference1.wsPeriodeID wsPeriodeID;
        
        public Release_wsPeriodeRequest()
        {
        }
        
        public Release_wsPeriodeRequest(ServiceReference1.wsPeriodeID wsPeriodeID)
        {
            this.wsPeriodeID = wsPeriodeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Release_wsPeriodeResponse", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/wsPeriode", IsWrapped=true)]
    public partial class Release_wsPeriodeResponse
    {
        
        public Release_wsPeriodeResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode")]
    public partial class periodeID
    {
        
        private string uUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePO_periode", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/wsPeriode", IsWrapped=true)]
    public partial class CreatePO_periodeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/wsPeriode")]
        public ServiceReference1.wsPeriodeID wsPeriodeID;
        
        public CreatePO_periodeRequest()
        {
        }
        
        public CreatePO_periodeRequest(ServiceReference1.wsPeriodeID wsPeriodeID)
        {
            this.wsPeriodeID = wsPeriodeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePO_periodeResponse", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/wsPeriode", IsWrapped=true)]
    public partial class CreatePO_periodeResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode")]
        public ServiceReference1.periodeID periodeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/wsPeriode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        public CreatePO_periodeResponse()
        {
        }
        
        public CreatePO_periodeResponse(ServiceReference1.periodeID periodeID, string result)
        {
            this.periodeID = periodeID;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface wsPeriodeObjChannel : ServiceReference1.wsPeriodeObj, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class wsPeriodeObjClient : System.ServiceModel.ClientBase<ServiceReference1.wsPeriodeObj>, ServiceReference1.wsPeriodeObj
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsPeriodeObjClient() : 
                base(wsPeriodeObjClient.GetDefaultBinding(), wsPeriodeObjClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.wsPeriodeObj.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPeriodeObjClient(EndpointConfiguration endpointConfiguration) : 
                base(wsPeriodeObjClient.GetBindingForEndpoint(endpointConfiguration), wsPeriodeObjClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPeriodeObjClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsPeriodeObjClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPeriodeObjClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsPeriodeObjClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPeriodeObjClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.Connect_wsPeriodeResponse ServiceReference1.wsPeriodeObj.Connect_wsPeriode(ServiceReference1.Connect_wsPeriodeRequest request)
        {
            return base.Channel.Connect_wsPeriode(request);
        }
        
        public ServiceReference1.wsPeriodeID Connect_wsPeriode(string userId, string password, string appServerInfo)
        {
            ServiceReference1.Connect_wsPeriodeRequest inValue = new ServiceReference1.Connect_wsPeriodeRequest();
            inValue.userId = userId;
            inValue.password = password;
            inValue.appServerInfo = appServerInfo;
            ServiceReference1.Connect_wsPeriodeResponse retVal = ((ServiceReference1.wsPeriodeObj)(this)).Connect_wsPeriode(inValue);
            return retVal.wsPeriodeID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Connect_wsPeriodeResponse> ServiceReference1.wsPeriodeObj.Connect_wsPeriodeAsync(ServiceReference1.Connect_wsPeriodeRequest request)
        {
            return base.Channel.Connect_wsPeriodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Connect_wsPeriodeResponse> Connect_wsPeriodeAsync(string userId, string password, string appServerInfo)
        {
            ServiceReference1.Connect_wsPeriodeRequest inValue = new ServiceReference1.Connect_wsPeriodeRequest();
            inValue.userId = userId;
            inValue.password = password;
            inValue.appServerInfo = appServerInfo;
            return ((ServiceReference1.wsPeriodeObj)(this)).Connect_wsPeriodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.Release_wsPeriodeResponse ServiceReference1.wsPeriodeObj.Release_wsPeriode(ServiceReference1.Release_wsPeriodeRequest request)
        {
            return base.Channel.Release_wsPeriode(request);
        }
        
        public void Release_wsPeriode(ServiceReference1.wsPeriodeID wsPeriodeID)
        {
            ServiceReference1.Release_wsPeriodeRequest inValue = new ServiceReference1.Release_wsPeriodeRequest();
            inValue.wsPeriodeID = wsPeriodeID;
            ServiceReference1.Release_wsPeriodeResponse retVal = ((ServiceReference1.wsPeriodeObj)(this)).Release_wsPeriode(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Release_wsPeriodeResponse> ServiceReference1.wsPeriodeObj.Release_wsPeriodeAsync(ServiceReference1.Release_wsPeriodeRequest request)
        {
            return base.Channel.Release_wsPeriodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Release_wsPeriodeResponse> Release_wsPeriodeAsync(ServiceReference1.wsPeriodeID wsPeriodeID)
        {
            ServiceReference1.Release_wsPeriodeRequest inValue = new ServiceReference1.Release_wsPeriodeRequest();
            inValue.wsPeriodeID = wsPeriodeID;
            return ((ServiceReference1.wsPeriodeObj)(this)).Release_wsPeriodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.CreatePO_periodeResponse ServiceReference1.wsPeriodeObj.CreatePO_periode(ServiceReference1.CreatePO_periodeRequest request)
        {
            return base.Channel.CreatePO_periode(request);
        }
        
        public ServiceReference1.periodeID CreatePO_periode(ServiceReference1.wsPeriodeID wsPeriodeID, out string result)
        {
            ServiceReference1.CreatePO_periodeRequest inValue = new ServiceReference1.CreatePO_periodeRequest();
            inValue.wsPeriodeID = wsPeriodeID;
            ServiceReference1.CreatePO_periodeResponse retVal = ((ServiceReference1.wsPeriodeObj)(this)).CreatePO_periode(inValue);
            result = retVal.result;
            return retVal.periodeID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CreatePO_periodeResponse> ServiceReference1.wsPeriodeObj.CreatePO_periodeAsync(ServiceReference1.CreatePO_periodeRequest request)
        {
            return base.Channel.CreatePO_periodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreatePO_periodeResponse> CreatePO_periodeAsync(ServiceReference1.wsPeriodeID wsPeriodeID)
        {
            ServiceReference1.CreatePO_periodeRequest inValue = new ServiceReference1.CreatePO_periodeRequest();
            inValue.wsPeriodeID = wsPeriodeID;
            return ((ServiceReference1.wsPeriodeObj)(this)).CreatePO_periodeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsPeriodeObj))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsPeriodeObj))
            {
                return new System.ServiceModel.EndpointAddress("http://www.virtic24.com/wsa/wsa1");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return wsPeriodeObjClient.GetBindingForEndpoint(EndpointConfiguration.wsPeriodeObj);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return wsPeriodeObjClient.GetEndpointAddress(EndpointConfiguration.wsPeriodeObj);
        }
        
        public enum EndpointConfiguration
        {
            
            wsPeriodeObj,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode", ConfigurationName="ServiceReference1.periodeObj")]
    public interface periodeObj
    {
        
        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Wrappernamespace (http://www.virtic.com/xmlns/virsapPeriode/periode) der Nachricht Release_periodeRequest nicht mit dem Standardwert (http://www.virtic.com/xmlns/virsapPeriode) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.Release_periodeResponse Release_periode(ServiceReference1.Release_periodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.Release_periodeResponse> Release_periodeAsync(ServiceReference1.Release_periodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.fetchV100Response fetchV100(ServiceReference1.fetchV100Request request);
        
        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Vorgang mehrere Rückgabewerte aufweist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.fetchV100Response> fetchV100Async(ServiceReference1.fetchV100Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.getDataResponse getData(ServiceReference1.getDataRequest request);
        
        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Vorgang mehrere Rückgabewerte aufweist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getDataResponse> getDataAsync(ServiceReference1.getDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.getPerExchangeDeadlinesV100Response getPerExchangeDeadlinesV100(ServiceReference1.getPerExchangeDeadlinesV100Request request);
        
        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Vorgang mehrere Rückgabewerte aufweist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getPerExchangeDeadlinesV100Response> getPerExchangeDeadlinesV100Async(ServiceReference1.getPerExchangeDeadlinesV100Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.getStructureResponse getStructure(ServiceReference1.getStructureRequest request);
        
        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Vorgang mehrere Rückgabewerte aufweist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getStructureResponse> getStructureAsync(ServiceReference1.getStructureRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Release_periode", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/periode", IsWrapped=true)]
    public partial class Release_periodeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode")]
        public ServiceReference1.periodeID periodeID;
        
        public Release_periodeRequest()
        {
        }
        
        public Release_periodeRequest(ServiceReference1.periodeID periodeID)
        {
            this.periodeID = periodeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Release_periodeResponse", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/periode", IsWrapped=true)]
    public partial class Release_periodeResponse
    {
        
        public Release_periodeResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode")]
    public partial class periodeV100OutRow
    {
        
        private System.Nullable<long> firObjIdField;
        
        private System.Nullable<long> perObjIdField;
        
        private System.Nullable<int> perMonatField;
        
        private System.Nullable<int> perJahrField;
        
        private System.Nullable<System.DateTime> perStartField;
        
        private System.Nullable<System.DateTime> perEndeField;
        
        private System.Nullable<bool> perEroeffnetField;
        
        private System.Nullable<bool> perGebuchtField;
        
        private System.Nullable<bool> perGeschlossenField;
        
        private System.Nullable<bool> lTransOkField;
        
        private string cErrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> firObjId
        {
            get
            {
                return this.firObjIdField;
            }
            set
            {
                this.firObjIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> perObjId
        {
            get
            {
                return this.perObjIdField;
            }
            set
            {
                this.perObjIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> perMonat
        {
            get
            {
                return this.perMonatField;
            }
            set
            {
                this.perMonatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> perJahr
        {
            get
            {
                return this.perJahrField;
            }
            set
            {
                this.perJahrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> perStart
        {
            get
            {
                return this.perStartField;
            }
            set
            {
                this.perStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> perEnde
        {
            get
            {
                return this.perEndeField;
            }
            set
            {
                this.perEndeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> perEroeffnet
        {
            get
            {
                return this.perEroeffnetField;
            }
            set
            {
                this.perEroeffnetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> perGebucht
        {
            get
            {
                return this.perGebuchtField;
            }
            set
            {
                this.perGebuchtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> perGeschlossen
        {
            get
            {
                return this.perGeschlossenField;
            }
            set
            {
                this.perGeschlossenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<bool> lTransOk
        {
            get
            {
                return this.lTransOkField;
            }
            set
            {
                this.lTransOkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string cErr
        {
            get
            {
                return this.cErrField;
            }
            set
            {
                this.cErrField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fetchV100", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/periode", IsWrapped=true)]
    public partial class fetchV100Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode")]
        public ServiceReference1.periodeID periodeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> iObjId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cFremdId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cQueryString;
        
        public fetchV100Request()
        {
        }
        
        public fetchV100Request(ServiceReference1.periodeID periodeID, System.Nullable<long> iObjId, string cFremdId, string cQueryString)
        {
            this.periodeID = periodeID;
            this.iObjId = iObjId;
            this.cFremdId = cFremdId;
            this.cQueryString = cQueryString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fetchV100Response", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/periode", IsWrapped=true)]
    public partial class fetchV100Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference1.periodeV100OutRow[] periodeV100Out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cErr;
        
        public fetchV100Response()
        {
        }
        
        public fetchV100Response(string result, ServiceReference1.periodeV100OutRow[] periodeV100Out, string cErr)
        {
            this.result = result;
            this.periodeV100Out = periodeV100Out;
            this.cErr = cErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getData", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/periode", IsWrapped=true)]
    public partial class getDataRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode")]
        public ServiceReference1.periodeID periodeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> iObjId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cFremdId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cQueryString;
        
        public getDataRequest()
        {
        }
        
        public getDataRequest(ServiceReference1.periodeID periodeID, System.Nullable<long> iObjId, string cFremdId, string cQueryString)
        {
            this.periodeID = periodeID;
            this.iObjId = iObjId;
            this.cFremdId = cFremdId;
            this.cQueryString = cQueryString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataResponse", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/periode", IsWrapped=true)]
    public partial class getDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement periodeOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cErr;
        
        public getDataResponse()
        {
        }
        
        public getDataResponse(string result, System.Xml.XmlElement periodeOut, string cErr)
        {
            this.result = result;
            this.periodeOut = periodeOut;
            this.cErr = cErr;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode")]
    public partial class perExchangeV100Row
    {
        
        private System.Nullable<long> firObjIdField;
        
        private System.Nullable<long> perObjIdField;
        
        private System.Nullable<int> perMonatField;
        
        private System.Nullable<int> perJahrField;
        
        private System.Nullable<System.DateTime> perStartField;
        
        private System.Nullable<System.DateTime> perEndeField;
        
        private string perexAppField;
        
        private string perexProcessField;
        
        private string perexDirectionField;
        
        private System.Nullable<System.DateTime> perexdetStartField;
        
        private System.Nullable<System.DateTime> perexdetEndeField;
        
        private string perexBezField;
        
        private string perexRemarkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> firObjId
        {
            get
            {
                return this.firObjIdField;
            }
            set
            {
                this.firObjIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> perObjId
        {
            get
            {
                return this.perObjIdField;
            }
            set
            {
                this.perObjIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> perMonat
        {
            get
            {
                return this.perMonatField;
            }
            set
            {
                this.perMonatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> perJahr
        {
            get
            {
                return this.perJahrField;
            }
            set
            {
                this.perJahrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> perStart
        {
            get
            {
                return this.perStartField;
            }
            set
            {
                this.perStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> perEnde
        {
            get
            {
                return this.perEndeField;
            }
            set
            {
                this.perEndeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string perexApp
        {
            get
            {
                return this.perexAppField;
            }
            set
            {
                this.perexAppField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string perexProcess
        {
            get
            {
                return this.perexProcessField;
            }
            set
            {
                this.perexProcessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string perexDirection
        {
            get
            {
                return this.perexDirectionField;
            }
            set
            {
                this.perexDirectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> perexdetStart
        {
            get
            {
                return this.perexdetStartField;
            }
            set
            {
                this.perexdetStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<System.DateTime> perexdetEnde
        {
            get
            {
                return this.perexdetEndeField;
            }
            set
            {
                this.perexdetEndeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string perexBez
        {
            get
            {
                return this.perexBezField;
            }
            set
            {
                this.perexBezField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string perexRemark
        {
            get
            {
                return this.perexRemarkField;
            }
            set
            {
                this.perexRemarkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPerExchangeDeadlinesV100", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/periode", IsWrapped=true)]
    public partial class getPerExchangeDeadlinesV100Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode")]
        public ServiceReference1.periodeID periodeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> perObjId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> perMonat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> perJahr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string perexApp;
        
        public getPerExchangeDeadlinesV100Request()
        {
        }
        
        public getPerExchangeDeadlinesV100Request(ServiceReference1.periodeID periodeID, System.Nullable<long> perObjId, System.Nullable<int> perMonat, System.Nullable<int> perJahr, string perexApp)
        {
            this.periodeID = periodeID;
            this.perObjId = perObjId;
            this.perMonat = perMonat;
            this.perJahr = perJahr;
            this.perexApp = perexApp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPerExchangeDeadlinesV100Response", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/periode", IsWrapped=true)]
    public partial class getPerExchangeDeadlinesV100Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference1.perExchangeV100Row[] perExchangeV100;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cErr;
        
        public getPerExchangeDeadlinesV100Response()
        {
        }
        
        public getPerExchangeDeadlinesV100Response(string result, ServiceReference1.perExchangeV100Row[] perExchangeV100, string cErr)
        {
            this.result = result;
            this.perExchangeV100 = perExchangeV100;
            this.cErr = cErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStructure", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/periode", IsWrapped=true)]
    public partial class getStructureRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode")]
        public ServiceReference1.periodeID periodeID;
        
        public getStructureRequest()
        {
        }
        
        public getStructureRequest(ServiceReference1.periodeID periodeID)
        {
            this.periodeID = periodeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStructureResponse", WrapperNamespace="http://www.virtic.com/xmlns/virsapPeriode/periode", IsWrapped=true)]
    public partial class getStructureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement structureIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement structureOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtic.com/xmlns/virsapPeriode/periode", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cErr;
        
        public getStructureResponse()
        {
        }
        
        public getStructureResponse(string result, System.Xml.XmlElement structureIn, System.Xml.XmlElement structureOut, string cErr)
        {
            this.result = result;
            this.structureIn = structureIn;
            this.structureOut = structureOut;
            this.cErr = cErr;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface periodeObjChannel : ServiceReference1.periodeObj, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class periodeObjClient : System.ServiceModel.ClientBase<ServiceReference1.periodeObj>, ServiceReference1.periodeObj
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public periodeObjClient() : 
                base(periodeObjClient.GetDefaultBinding(), periodeObjClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.periodeObj.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public periodeObjClient(EndpointConfiguration endpointConfiguration) : 
                base(periodeObjClient.GetBindingForEndpoint(endpointConfiguration), periodeObjClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public periodeObjClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(periodeObjClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public periodeObjClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(periodeObjClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public periodeObjClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.Release_periodeResponse ServiceReference1.periodeObj.Release_periode(ServiceReference1.Release_periodeRequest request)
        {
            return base.Channel.Release_periode(request);
        }
        
        public void Release_periode(ServiceReference1.periodeID periodeID)
        {
            ServiceReference1.Release_periodeRequest inValue = new ServiceReference1.Release_periodeRequest();
            inValue.periodeID = periodeID;
            ServiceReference1.Release_periodeResponse retVal = ((ServiceReference1.periodeObj)(this)).Release_periode(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Release_periodeResponse> ServiceReference1.periodeObj.Release_periodeAsync(ServiceReference1.Release_periodeRequest request)
        {
            return base.Channel.Release_periodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Release_periodeResponse> Release_periodeAsync(ServiceReference1.periodeID periodeID)
        {
            ServiceReference1.Release_periodeRequest inValue = new ServiceReference1.Release_periodeRequest();
            inValue.periodeID = periodeID;
            return ((ServiceReference1.periodeObj)(this)).Release_periodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.fetchV100Response ServiceReference1.periodeObj.fetchV100(ServiceReference1.fetchV100Request request)
        {
            return base.Channel.fetchV100(request);
        }
        
        public string fetchV100(ServiceReference1.periodeID periodeID, System.Nullable<long> iObjId, string cFremdId, string cQueryString, out ServiceReference1.periodeV100OutRow[] periodeV100Out, out string cErr)
        {
            ServiceReference1.fetchV100Request inValue = new ServiceReference1.fetchV100Request();
            inValue.periodeID = periodeID;
            inValue.iObjId = iObjId;
            inValue.cFremdId = cFremdId;
            inValue.cQueryString = cQueryString;
            ServiceReference1.fetchV100Response retVal = ((ServiceReference1.periodeObj)(this)).fetchV100(inValue);
            periodeV100Out = retVal.periodeV100Out;
            cErr = retVal.cErr;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.fetchV100Response> fetchV100Async(ServiceReference1.fetchV100Request request)
        {
            return base.Channel.fetchV100Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.getDataResponse ServiceReference1.periodeObj.getData(ServiceReference1.getDataRequest request)
        {
            return base.Channel.getData(request);
        }
        
        public string getData(ServiceReference1.periodeID periodeID, System.Nullable<long> iObjId, string cFremdId, string cQueryString, out System.Xml.XmlElement periodeOut, out string cErr)
        {
            ServiceReference1.getDataRequest inValue = new ServiceReference1.getDataRequest();
            inValue.periodeID = periodeID;
            inValue.iObjId = iObjId;
            inValue.cFremdId = cFremdId;
            inValue.cQueryString = cQueryString;
            ServiceReference1.getDataResponse retVal = ((ServiceReference1.periodeObj)(this)).getData(inValue);
            periodeOut = retVal.periodeOut;
            cErr = retVal.cErr;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getDataResponse> getDataAsync(ServiceReference1.getDataRequest request)
        {
            return base.Channel.getDataAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.getPerExchangeDeadlinesV100Response ServiceReference1.periodeObj.getPerExchangeDeadlinesV100(ServiceReference1.getPerExchangeDeadlinesV100Request request)
        {
            return base.Channel.getPerExchangeDeadlinesV100(request);
        }
        
        public string getPerExchangeDeadlinesV100(ServiceReference1.periodeID periodeID, System.Nullable<long> perObjId, System.Nullable<int> perMonat, System.Nullable<int> perJahr, string perexApp, out ServiceReference1.perExchangeV100Row[] perExchangeV100, out string cErr)
        {
            ServiceReference1.getPerExchangeDeadlinesV100Request inValue = new ServiceReference1.getPerExchangeDeadlinesV100Request();
            inValue.periodeID = periodeID;
            inValue.perObjId = perObjId;
            inValue.perMonat = perMonat;
            inValue.perJahr = perJahr;
            inValue.perexApp = perexApp;
            ServiceReference1.getPerExchangeDeadlinesV100Response retVal = ((ServiceReference1.periodeObj)(this)).getPerExchangeDeadlinesV100(inValue);
            perExchangeV100 = retVal.perExchangeV100;
            cErr = retVal.cErr;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getPerExchangeDeadlinesV100Response> getPerExchangeDeadlinesV100Async(ServiceReference1.getPerExchangeDeadlinesV100Request request)
        {
            return base.Channel.getPerExchangeDeadlinesV100Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.getStructureResponse ServiceReference1.periodeObj.getStructure(ServiceReference1.getStructureRequest request)
        {
            return base.Channel.getStructure(request);
        }
        
        public string getStructure(ServiceReference1.periodeID periodeID, out System.Xml.XmlElement structureIn, out System.Xml.XmlElement structureOut, out string cErr)
        {
            ServiceReference1.getStructureRequest inValue = new ServiceReference1.getStructureRequest();
            inValue.periodeID = periodeID;
            ServiceReference1.getStructureResponse retVal = ((ServiceReference1.periodeObj)(this)).getStructure(inValue);
            structureIn = retVal.structureIn;
            structureOut = retVal.structureOut;
            cErr = retVal.cErr;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getStructureResponse> getStructureAsync(ServiceReference1.getStructureRequest request)
        {
            return base.Channel.getStructureAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.periodeObj))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.periodeObj))
            {
                return new System.ServiceModel.EndpointAddress("http://www.virtic24.com/wsa/wsa1");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return periodeObjClient.GetBindingForEndpoint(EndpointConfiguration.periodeObj);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return periodeObjClient.GetEndpointAddress(EndpointConfiguration.periodeObj);
        }
        
        public enum EndpointConfiguration
        {
            
            periodeObj,
        }
    }
}
